export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_BEDS = 'UPDATE_BEDS';
export const UPDATE_BATHS = 'UPDATE_BATHS';
export const UPDATE_PRICE = 'UPDATE_PRICE';
